import * as core from '@actions/core';
import * as github from '@actions/github';
import OpenAI from 'openai';

type Format = 'rap' | 'haiku' | 'roast';

interface PRSummary {
  title: string;
  body: string;
  diff: string;
  filesChanged: string[];
}

// Maximum diff characters to send to the LLM to keep costs low
const MAX_DIFF_CHARS = 3000;

const COMMENT_HEADERS: Record<Format, string> = {
  rap: '🎤 **Diff Cypher**',
  haiku: '🌸 **Diff Haiku**',
  roast: '🔥 **Code Roast**',
};

function buildPrompt(format: Format, summary: PRSummary, maxLines: number, tone: string): string {
  const toneNote = tone === 'playful' ? 'Use a very playful, exaggerated tone.' : 'Keep the tone humorous but respectful.';
  const context = `
PR Title: ${summary.title}
PR Description: ${summary.body || '(none)'}
Files changed: ${summary.filesChanged.join(', ') || '(unknown)'}

Diff excerpt:
${summary.diff}
`.trim();

  switch (format) {
    case 'rap':
      return `You are a creative hip-hop lyricist. Write a short rap verse summarizing this GitHub pull request.

Requirements:
- ${maxLines} lines maximum
- Use rhyme and rhythm
- Mention the main code changes by name
- ${toneNote}
- No profanity
- Do not include a title or header, just the verse

${context}`;

    case 'haiku':
      return `You are a haiku poet. Write a haiku summarizing the key change in this GitHub pull request.

Format:
- Exactly 3 lines
- Approximate 5-7-5 syllable structure
- Focus on the main code change
- Do not include a title or header, just the 3 lines

${context}`;

    case 'roast':
      return `You are a playful battle-rap comedian. Write a roast of the code changes in this pull request.

Rules:
- Roast the code quality, patterns, or complexity — NOT the developer as a person
- Keep it lighthearted and funny
- ${maxLines} lines maximum
- No profanity, no harassment, no personal attacks
- Do not include a title or header, just the roast

${context}`;
  }
}

function summarizeDiff(rawDiff: string, filesChanged: string[]): string {
  if (rawDiff.length <= MAX_DIFF_CHARS) {
    return rawDiff;
  }

  // Truncate large diffs, keeping the beginning which usually has the most signal
  const truncated = rawDiff.slice(0, MAX_DIFF_CHARS);
  const lastNewline = truncated.lastIndexOf('\n');
  const clean = lastNewline > 0 ? truncated.slice(0, lastNewline) : truncated;
  return `${clean}\n\n[diff truncated — ${filesChanged.length} files changed total]`;
}

async function fetchPRData(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number
): Promise<PRSummary> {
  const { data: pr } = await octokit.rest.pulls.get({ owner, repo, pull_number: prNumber });

  // Fetch the diff
  const { data: diffData } = await octokit.rest.pulls.get({
    owner,
    repo,
    pull_number: prNumber,
    mediaType: { format: 'diff' },
  });

  // Fetch all changed files (paginate so large PRs aren't silently truncated)
  const files = await octokit.paginate(octokit.rest.pulls.listFiles, {
    owner,
    repo,
    pull_number: prNumber,
    per_page: 100,
  });

  const filesChanged = files.map(f => f.filename);
  const rawDiff = typeof diffData === 'string' ? diffData : JSON.stringify(diffData);

  return {
    title: pr.title,
    body: pr.body ?? '',
    diff: summarizeDiff(rawDiff, filesChanged),
    filesChanged,
  };
}

async function callLLM(apiKey: string, model: string, prompt: string): Promise<string> {
  const client = new OpenAI({ apiKey });

  const response = await client.chat.completions.create({
    model,
    messages: [{ role: 'user', content: prompt }],
    max_tokens: 300,
    temperature: 0.85,
  });

  const text = response.choices[0]?.message?.content?.trim();
  if (!text) {
    throw new Error('LLM returned an empty response');
  }
  return text;
}

async function postComment(
  octokit: ReturnType<typeof github.getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
  format: Format,
  content: string
): Promise<void> {
  const header = COMMENT_HEADERS[format];
  const body = `${header}\n\n${content}\n\n---\n*Generated by [spit-the-diff](https://github.com/ssfinney/spit-the-diff)*`;

  await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body,
  });
}

async function run(): Promise<void> {
  const format = (core.getInput('format') || 'rap') as Format;
  const model = core.getInput('model') || 'gpt-4o-mini';
  const maxLines = parseInt(core.getInput('max_lines') || '8', 10);
  const tone = core.getInput('tone') || 'friendly';
  const openaiApiKey = core.getInput('openai_api_key');
  const githubToken = core.getInput('github_token') || process.env.GITHUB_TOKEN;

  if (!openaiApiKey) {
    core.setFailed('openai_api_key input is required');
    return;
  }

  if (!githubToken) {
    core.setFailed('github_token is required (or GITHUB_TOKEN env var)');
    return;
  }

  const ctx = github.context;
  const pr = ctx.payload.pull_request;

  if (!pr) {
    core.setFailed('This action only runs on pull_request events');
    return;
  }

  const octokit = github.getOctokit(githubToken);
  const { owner, repo } = ctx.repo;
  const prNumber = pr.number as number;

  core.info(`Analyzing PR #${prNumber}: ${pr.title}`);

  // Detect roast-me label — overrides the format input
  const labels: string[] = (pr.labels ?? []).map((l: { name?: string }) => l.name ?? '');
  const effectiveFormat: Format = labels.includes('roast-me') ? 'roast' : format;

  if (effectiveFormat === 'roast') {
    core.info('roast-me label detected — switching to roast mode');
  }

  core.info('Fetching PR diff...');
  const summary = await fetchPRData(octokit, owner, repo, prNumber);

  core.info(`Building ${effectiveFormat} prompt...`);
  const prompt = buildPrompt(effectiveFormat, summary, maxLines, tone);

  core.info(`Calling ${model}...`);
  const creative = await callLLM(openaiApiKey, model, prompt);

  core.info('Posting comment to PR...');
  await postComment(octokit, owner, repo, prNumber, effectiveFormat, creative);

  core.info('Done! Your diff just dropped bars.');
}

run().catch(err => {
  core.setFailed(err instanceof Error ? err.message : String(err));
});
